#!/bin/sh
set -e
./gradlew publishKotlinMavenPublicationToMavenCentralRepository
./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET || true
